version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.0
    environment:
        BASH_ENV: ~/.bashrc
    steps:
      - checkout
      - run:
          name: Dependencies
          command: pip3 install --user circleci -r requirements.txt
  test:
    docker:
      - image: circleci/python:3.6.0
    steps:
      - checkout
      - run:
          command: python3.6 -B -m unittest discover -s tests -t .
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
